### PR TITLE
fix: incorrect ordering

### PR DESCRIPTION
**Pull request by JarKz**
In lua multiline string doesn't have access by keys. And every accessing is `nil`, so every result is zero. That is incorrect.

I changed it to table, which contains keys as template key and values is increasing numbers.

Also added capitalizing for keys.

### CODE REVIEW

**Comment by wintermute-cell** [comment]
Thank you!

I don't have access to a computer right now to check this myself; do you mean that `order[right]` and `order[left]` would always be `nil` without your fix?

```lua
    table.sort(s, function (left, right) 
         return (order[left] or 0) < (order[right] or 0)
```

**Comment by wintermute-cell** [comment]
Thank you again! 

Oh yes right, I see that the current version is stupid; I think I forgot to split the string into a table before working with it.

Manually fixing the order.lua file is not the way to go here though. That file is generated by `refresh_templates.sh`, and would be overwritten in the future. What needs to happen is either an adjustment to the bash script, or preferrably some lua code that splits the string by its linebreaks (`\n`) and removes the empty lines.

**Comment by JarKz** [comment]
Yes, that is!
I found it when I tried to make gitignore with Java, Gradle list and
without my fix order always is "Gradle, Java". And because of this my
gradle-wrapper.jar is not recognized :(

вс, 27 авг. 2023 г. в 17:16, wintermute ***@***.***>:

**Comment by JarKz** [comment]
I changed the bash script. It make right order.lua file as table.
All is described in commit.

**Comment by JarKz** [comment]
I have a solution for logic capitalizing for subwords like "***A***ndroid***S***tudio".
Motivation: I don't like the `:lower()` method, because performance will be down. Even if it runs once.

My solution based on associative array in bash. Firstly script loops all files except "order"and each base name (without extensions) will maps to array by rule: `{lower_case_basename}={normal_case_basename}`.
And after looping I check existence of file `order`. If exists, I will loop lines from this file and change lowercase words to capitalized case by the associative array.

For me it look very good. But, I want to ask you about versioning. As far I know, MacOS have default bash version 3.X, which doesn't contains associative arrays. I don't know what about Linux, maybe some distributions have older bash version.

If you have no complaints about it, I will commit it because it is done.
UPD: typo

**Pull request merged**
